In [1]:
"""
------------------------------------------------------------------------------
QLCA Data Preparation

Preparation of the QLCA dataset used for further analysis.

The data is extracted from the Excel file
`Q-LCA_FD3_Bilanzierungstool.xlsx`, using Tables 4, 8 and 9.

The workflow includes:
- identification of relevant tables and variables
- extraction and combination of the required data
- selection of relevant columns
- data cleaning and preparation for further analysis
------------------------------------------------------------------------------
"""

'\n------------------------------------------------------------------------------\nQLCA Data Preparation\n\nPreparation of the QLCA dataset used for further analysis.\n\nThe data is extracted from the Excel file\n`Q-LCA_FD3_Bilanzierungstool.xlsx`, using Tables 4, 8 and 9.\n\nThe workflow includes:\n- identification of relevant tables and variables\n- extraction and combination of the required data\n- selection of relevant columns\n- data cleaning and preparation for further analysis\n------------------------------------------------------------------------------\n'

In [2]:
"""
------------------------------------------------------------------------------
Libraries
------------------------------------------------------------------------------
"""

import pandas as pd
import numpy as np

In [3]:
"""
------------------------------------------------------------------------------
Table 8: Abs_Kod_Matrix_Siedlung / 972 Neighbourhood scenarios
------------------------------------------------------------------------------
"""

# Show all columns
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# 6ha-Table
df_8_Matrix = pd.read_excel("../data/raw/Q-LCA_FD3_Bilanzierungstool.xlsx", sheet_name="8 - Abs_Kod_Matrix_Siedlung", skiprows =1)
df_8_Matrix.columns = df_8_Matrix.columns.str.replace("\n", " ").str.strip()

df_8_Matrix.head()

,Siedlungs-Code,Flächen-Code,B6-Code,Dachform,Geschoss-Code,Unnamed: 5,Unnamed: 6,Dach-Code,Typ,Bauart,Energiebedarf,Typ.1,Bauart.1,Energiebedarf.1,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haus- technik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiers strom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Unnamed: 53
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EH15NgGi,EgGi,E15N,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,Einfamilienhaus,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119.154919,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.086646,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18886.967188,18886.967188,0.0,NaN
2,EH15LgGi,EgGi,E15L,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,LW Wärmepumpe,gering,Kreuzung,Gitter,117034.638730,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8861.989437,855.0,4757.375085,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24150.548207,24150.548207,0.0,NaN
3,EH15EgGi,EgGi,E15E,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,Erdgas,gering,Kreuzung,Gitter,139370.376391,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.358409,855.0,7952.744057,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43290.916896,43290.916896,0.0,NaN
4,EH30NgGi,EgGi,E30N,Sattel,1.5,gering,Hg30,HS30,EFH,Holz,30 kWh,NaN,NaN,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906.089612,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.719985,855.0,62566.105633,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168.013342,29168.013342,0.0,NaN

In [4]:
# Delete all Nan row
df_8_Matrix = df_8_Matrix.dropna(how="all")

# Delete all Nan columns
df_8_Matrix = df_8_Matrix.dropna(axis=1, how="all")

df_8_Matrix.head()

,Siedlungs-Code,Flächen-Code,B6-Code,Dachform,Geschoss-Code,Unnamed: 5,Unnamed: 6,Dach-Code,Typ,Bauart,Energiebedarf,Typ.1,Bauart.1,Energiebedarf.1,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haus- technik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiers strom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Unnamed: 53
1,EH15NgGi,EgGi,E15N,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,Einfamilienhaus,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119.154919,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.086646,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18886.967188,18886.967188,0.0,NaN
2,EH15LgGi,EgGi,E15L,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,LW Wärmepumpe,gering,Kreuzung,Gitter,117034.638730,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8861.989437,855.0,4757.375085,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24150.548207,24150.548207,0.0,NaN
3,EH15EgGi,EgGi,E15E,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,Erdgas,gering,Kreuzung,Gitter,139370.376391,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.358409,855.0,7952.744057,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43290.916896,43290.916896,0.0,NaN
4,EH30NgGi,EgGi,E30N,Sattel,1.5,gering,Hg30,HS30,EFH,Holz,30 kWh,NaN,NaN,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906.089612,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.719985,855.0,62566.105633,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168.013342,29168.013342,0.0,NaN
5,EH30LgGi,EgGi,E30L,Sattel,1.5,gering,Hg30,HS30,EFH,Holz,30 kWh,NaN,NaN,NaN,LW Wärmepumpe,gering,Kreuzung,Gitter,128443.352089,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.191858,855.0,4974.577506,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37296.803945,37296.803945,0.0,NaN

In [5]:
# Clean tabs and spaces from column names
df_8_Matrix.columns = (
    df_8_Matrix.columns
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

df_8_Matrix.head()

,Siedlungs-Code,Flächen-Code,B6-Code,Dachform,Geschoss-Code,Unnamed: 5,Unnamed: 6,Dach-Code,Typ,Bauart,Energiebedarf,Typ.1,Bauart.1,Energiebedarf.1,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haus- technik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiers strom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Unnamed: 53
1,EH15NgGi,EgGi,E15N,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,Einfamilienhaus,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119.154919,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.086646,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18886.967188,18886.967188,0.0,NaN
2,EH15LgGi,EgGi,E15L,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,LW Wärmepumpe,gering,Kreuzung,Gitter,117034.638730,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8861.989437,855.0,4757.375085,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24150.548207,24150.548207,0.0,NaN
3,EH15EgGi,EgGi,E15E,Sattel,1.5,gering,Hg15,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,Erdgas,gering,Kreuzung,Gitter,139370.376391,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.358409,855.0,7952.744057,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43290.916896,43290.916896,0.0,NaN
4,EH30NgGi,EgGi,E30N,Sattel,1.5,gering,Hg30,HS30,EFH,Holz,30 kWh,NaN,NaN,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906.089612,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.719985,855.0,62566.105633,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168.013342,29168.013342,0.0,NaN
5,EH30LgGi,EgGi,E30L,Sattel,1.5,gering,Hg30,HS30,EFH,Holz,30 kWh,NaN,NaN,NaN,LW Wärmepumpe,gering,Kreuzung,Gitter,128443.352089,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.191858,855.0,4974.577506,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37296.803945,37296.803945,0.0,NaN

In [6]:
# Rename unnamed columns
df_8_Matrix = df_8_Matrix.rename(columns={
    "Geschoss-Code": "Geschoss-Code_1",
    "Unnamed: 5": "Geschoss-Code_2",
    "Unnamed: 6": "Geschoss-Code_3"
})

# Combine
df_8_Matrix["Geschoss-Code"] = (
    df_8_Matrix[["Geschoss-Code_1", "Geschoss-Code_2", "Geschoss-Code_3"]]
    .fillna("")
    .astype(str)
    .agg("-".join, axis=1)
)

# Drop columns
df_8_Matrix = df_8_Matrix.drop(columns=[
    "Geschoss-Code_1",
    "Geschoss-Code_2",
    "Geschoss-Code_3"
])


df_8_Matrix.head()

,Siedlungs-Code,Flächen-Code,B6-Code,Dachform,Dach-Code,Typ,Bauart,Energiebedarf,Typ.1,Bauart.1,Energiebedarf.1,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haus- technik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiers strom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Unnamed: 53,Geschoss-Code
1,EH15NgGi,EgGi,E15N,Sattel,HS15,EFH,Holz,15 kWh,Einfamilienhaus,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119.154919,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.086646,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18886.967188,18886.967188,0.0,NaN,1.5-gering-Hg15
2,EH15LgGi,EgGi,E15L,Sattel,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,LW Wärmepumpe,gering,Kreuzung,Gitter,117034.638730,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8861.989437,855.0,4757.375085,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24150.548207,24150.548207,0.0,NaN,1.5-gering-Hg15
3,EH15EgGi,EgGi,E15E,Sattel,HS15,EFH,Holz,15 kWh,NaN,NaN,NaN,Erdgas,gering,Kreuzung,Gitter,139370.376391,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.358409,855.0,7952.744057,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43290.916896,43290.916896,0.0,NaN,1.5-gering-Hg15
4,EH30NgGi,EgGi,E30N,Sattel,HS30,EFH,Holz,30 kWh,NaN,NaN,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906.089612,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.719985,855.0,62566.105633,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168.013342,29168.013342,0.0,NaN,1.5-gering-Hg30
5,EH30LgGi,EgGi,E30L,Sattel,HS30,EFH,Holz,30 kWh,NaN,NaN,NaN,LW Wärmepumpe,gering,Kreuzung,Gitter,128443.352089,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.191858,855.0,4974.577506,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37296.803945,37296.803945,0.0,NaN,1.5-gering-Hg30

In [7]:
print(df_8_Matrix.columns.tolist())

['Siedlungs-Code', 'Flächen-Code', 'B6-Code', 'Dachform', 'Dach-Code', 'Typ', 'Bauart', 'Energiebedarf', 'Typ.1', 'Bauart.1', 'Energiebedarf.1', 'Versorgungsart', 'Dichte', 'Erschließung (Segm.)', 'Erschließung (Sied.)', 'GWP', 'GWP ohne Strom', 'GWP für Bauwerk (KG 300)', '310 Erdaushub Keller', '322 Bodenplatte', '325 Bodenbelag', '331 Außenwand', '334 Außentüren', '339 Kellerwände', '334 Fenster', '341 Innenwände tragend (inkl. Aufzugschacht)', '342 Innen wände', '344 Innen türen', '351 Decken', '351 Treppe', '361 Dach', 'GWP für Haus- technik (KG 400)', '410 Abwasser, Trinkwasser', '420 Wärme- versorgung', '430 Lüftung', '440 Strom', '460 Aufzug', 'GWP für gesamte Geb.- Erschliessung (KG 500)', '500 Quartiers strom', '500 Quartierswasserleitung', '510 Erdaushub Leitungen', '510 Erdaushub Garagen', '521 Gehweg Radweg', '522 Straße', '524 Stell -plätze', '524 Hoch garagen', '524 Tief garagen', 'Summe Betrieb & Nutzstrom', 'GWP für Wärmeversorgung (B6)', 'GWP für Nutzstrom', 'Unnamed: 53', 'Geschoss-Code']

In [8]:
relevant_cols = [
    "Siedlungs-Code",
    "Flächen-Code",
    "Typ",
    "Bauart",
    "Energiebedarf",
    "Versorgungsart",
    "Dichte",
    "Erschließung (Segm.)",
    "Erschließung (Sied.)",
    "GWP",
    "GWP ohne Strom",
    "GWP für Bauwerk (KG 300)",
    "310 Erdaushub Keller",
    "322 Bodenplatte",
    "325 Bodenbelag",
    "331 Außenwand",
    "334 Außentüren",
    "339 Kellerwände",
    "334 Fenster",
    "341 Innenwände tragend (inkl. Aufzugschacht)",
    "342 Innen wände",
    "344 Innen türen",
    "351 Decken",
    "351 Treppe",
    "361 Dach",
    "GWP für Haus- technik (KG 400)",
    "410 Abwasser, Trinkwasser",
    "420 Wärme- versorgung",
    "430 Lüftung",
    "440 Strom",
    "460 Aufzug",
    "GWP für gesamte Geb.- Erschliessung (KG 500)",
    "500 Quartiers strom",
    "500 Quartierswasserleitung",
    "510 Erdaushub Leitungen",
    "510 Erdaushub Garagen",
    "521 Gehweg Radweg",
    "522 Straße",
    "524 Stell -plätze",
    "524 Hoch garagen",
    "524 Tief garagen",
    "Summe Betrieb & Nutzstrom",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom"
]

df_8 = df_8_Matrix[relevant_cols].copy()

df_8.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haus- technik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiers strom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom
1,EH15NgGi,EgGi,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119.154919,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.086646,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18886.967188,18886.967188,0.0
2,EH15LgGi,EgGi,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117034.638730,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8861.989437,855.0,4757.375085,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24150.548207,24150.548207,0.0
3,EH15EgGi,EgGi,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370.376391,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.358409,855.0,7952.744057,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43290.916896,43290.916896,0.0
4,EH30NgGi,EgGi,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906.089612,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.719985,855.0,62566.105633,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168.013342,29168.013342,0.0
5,EH30LgGi,EgGi,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443.352089,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.191858,855.0,4974.577506,1772.6688,1476.945552,0.0,25140.126,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37296.803945,37296.803945,0.0

In [9]:
# Rename columns
df_8 = df_8.rename(columns={

    # KG 400
    "GWP für Haus- technik (KG 400)": "GWP für Haustechnik (KG 400)",

    # KG500
    "500 Quartiers strom": "500 Quartiersstrom"
}
)

In [10]:
print(df_8["524 Hoch garagen"].dtype)

float64

In [11]:
df_8["524 Hoch garagen"].astype(str).unique()[:20]

<StringArray>
[            '3024.0', '3628.7999999999997',  '4989.599999999999',
                '0.0', '2620.7999999999997',  '4233.599999999999',
             '3225.6', '4082.3999999999996',             '4838.4',
  '7257.599999999999',             '4435.2',  '6249.599999999999',
             '2822.4',             '5644.8',             '6048.0',
             '9072.0',             '3427.2',  '5241.599999999999',
             '7812.0',             '7056.0']
Length: 20, dtype: str

In [12]:
print(df_8["GWP"].dtype)
print(df_8["GWP für Bauwerk (KG 300)"].dtype)
print(df_8["GWP für Haustechnik (KG 400)"].dtype)
print(df_8["GWP für gesamte Geb.- Erschliessung (KG 500)"].dtype)
print(df_8["Summe Betrieb & Nutzstrom"].dtype)

float64
float64
float64
float64
float64

In [13]:
df_8["GWP"] = df_8["GWP"].round(0).astype("Int64")

df_8["GWP für Bauwerk (KG 300)"] = df_8["GWP für Bauwerk (KG 300)"].astype("float")

df_8["GWP für Haustechnik (KG 400)"] = df_8["GWP für Haustechnik (KG 400)"].round(1).astype("Float64")

df_8["GWP für gesamte Geb.- Erschliessung (KG 500)"] = df_8["GWP für gesamte Geb.- Erschliessung (KG 500)"].round(0).astype("Int64")

df_8["Summe Betrieb & Nutzstrom"]= df_8["Summe Betrieb & Nutzstrom"].round(0).astype("Int64")

In [14]:
df_8.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom
1,EH15NgGi,EgGi,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0
2,EH15LgGi,EgGi,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0
3,EH15EgGi,EgGi,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0
4,EH30NgGi,EgGi,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0
5,EH30LgGi,EgGi,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0

In [15]:
# Test
S1 = {
    "Typ": "ZH",
    "Bauart": "Massiv",
    "Energiebedarf": "70 kWh",
    "Versorgungsart": "Erdgas",
    "Dichte": "hoch",
    "Erschließung (Sied.)": "Gitter"
}

df_S1 = df_8.copy()

for key, value in S1.items():
    df_S1 = df_S1[df_S1[key] == value]

df_S1

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom
720,ZM70EhGi,ZhGi,ZH,Massiv,70 kWh,Erdgas,hoch,Kreuzung,Gitter,2055978,2.055978e+06,461027.912519,4160.279631,32717.52,58599.307385,71813.847877,7939.938462,17982.0,39965.862857,61196.112,29483.003077,1507.347692,99396.293538,3898.8,32367.6,116087.5,369.36,53409.49057,32920.4736,14678.623606,14709.6,188532,437.388,1368.0,42.672,10197.207138,6647.34,8310.96,5140.8,0.0,156387.323077,1290330,1.290330e+06,0.0

In [16]:
"""
------------------------------------------------------------------------------
Table 4: Flächencode / Area code
------------------------------------------------------------------------------
"""

# Excel
df_4_Flaechencode = pd.read_excel("../data/raw/4_Flaechencode.xlsx")

df_4_Flaechencode.head()

,Flächen-Code,Nr.,Gebäudetyp,Dichte,Straßenform/ Erschließungstyp,Unnamed: 5,Gesamtfläche,Baufelder und sonstige Freiflächen,Straßenflächen (öffentlich),Rad- und Gehweg- flächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Garagengrundflächen (brutto) (1),Anteil überbaute Flächen gesamt,Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Kellerflächen (brutto) (4),Kellerflächen netto (5),Aushubvolumen (m3),Unnamed: 19,Summe aller überbauter Teilflächen (m²),Quartiers-GRZ,Quartiers-GFZ,Unnamed: 23,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,NRF (m²) inkl. oberirdische Garagen (5),BGF (m²) Wohnen (inkl. Keller),Nettoraumfläche NRF (m2),Nettowohnfläche NUF (m2),davon NRF (m²) Balkone (6),davon NRF (m²) Wohnen Innenräume (7),Unnamed: 32,Grundflächen (brutto),Dachflächen,Fassadenflächen,Hüllflächen gesamt (mit Bodenplatte),Volumen (m³),A/V-Verhältnis Wohngebäude,Unnamed: 39,Länge Straßen (mittig Straße),Zuwege zu den Gebäuden (von Häusern zur Straßenmitte) (lfm),Netzlänge gesamt (Straßenlängen (mittig) + Zuwege) (lfm),Unnamed: 43,Anzahl Gebäude/ Kachel,Unnamed: 45,Nettowohnfläche pro Person (8) (statistisch),WFL/WE (m²) (9) (statistisch),BGF/WE (10) (rechnerisch aus Statistik abgeleitet),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Straßenfläche pro Bewohner (m²),Straßenfläche pro WE (m²),Unnamed: 53,Dachtyp,Bodenplatte - 320,Boden (m2) (alle Geschosse) - 320,Außenwände (m2) - 330,Außenwände abzügli. Fenster & Türen (m2) - 330,Kellerboden brutto (m2) - 320,Kellerwände (m2) - 330,Außentüren (Stk) - 330,Fensterflächenanteil (%) - 330,Außenfenster (m2) - 330,Tragende Innenwände abzügl. Türen (m2) - 340,Nichttragende Innenwände abzügl. Innentüren (m2) - 340,Innentüren (Stk) - 340,Decken (m2) - 350,Treppen (Stk) - 350,Dachkonstruktion (m2) - 360,Unnamed: 70,Lüftungskanal Länge (lm),Stromkabel lm,Steckdosen (Stk),Lichtschalter (Stk),Unnamed: 75,Aufzug (Stk),Unnamed: 77,Trinkwarmwasserbedarf (60 °C) gesamt in MWh pro Jahr,E-Kennwert,Wärmebedarf gesamt kWh/a,Installierte Leistung thermisch kW,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA,E-Kennwert.1,Wärmebedarf gesamt kWh/a.1,Installierte Leistung thermisch kW.1,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.1,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.1",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.1,E-Kennwert.2,Wärmebedarf gesamt kWh/a.2,Installierte Leistung thermisch kW.2,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.2,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.2",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.2,Jahresarbeitszahl Luft-Wasser-Wärmepumpe,Unnamed: 98,Trinkwarmwasserbedarf (60 °C) gesamt in MWh pro Jahr.1,E-Kennwert.3,Wärmebedarf gesamt kWh/a.3,Installierte Leistung thermisch kW.3,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.3,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.3",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.3,E-Kennwert.4,Wärmebedarf gesamt kWh/a.4,Installierte Leistung thermisch kW.4,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.4,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.4",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.4,E-Kennwert.5,Wärmebedarf gesamt kWh/a.5,Installierte Leistung thermisch kW.5,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.5,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.5",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.5,Jahresarbeitszahl Luft-Wasser-Wärmepumpe.1,Unnamed: 119,Trinkwarmwasserbedarf (60 °C) gesamt in MWh pro Jahr.2,E-Kennwert.6,Wärmebedarf gesamt kWh/a.6,Installierte Leistung thermisch kW.6,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.6,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.6",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.6,E-Kennwert.7,Wärmebedarf gesamt kWh/a.7,Installierte Leistung thermisch kW.7,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.7,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.7",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.7,E-Kennwert.8,Wärmebedarf gesamt kWh/a.8,Installierte Leistung thermisch kW.8,CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.8,"Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.8",GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.8,Jahresarbeitszahl Luft-Wasser-Wärmepumpe.2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EgKr,1.0,EFH,gering,Kreuzung,NaN,10000.0,7225.0,1164.0,931.0,680.0,977.0,150.0,0.1127,NaN,NaN,488.5,390.8,1465.5,NaN,1127.0,0.1127,0.16155,NaN,1.5,1615.5,1292.4,1954.0,1563.2,1172.4,25.0,1538.2,NaN,977.0,1357.0,1605.0,3939.0,5119.0,0.769486,NaN,200.0,125.0,325.0,NaN,10.0,NaN,51.0,157.0,196.0,22.988235,10.0,50.634596,116.4,NaN,Sattel,977.0,1152.4,NaN,NaN,488.5,NaN,20.0,0.2,234.48,360.0,764.0,80.0,663.9,10.0,NaN,NaN,351.72,6881.988,570.0,280.0,NaN,0.0,NaN,14720.6544,15.0,17601.0,9.257502,0.256995,NaN,792.895847,30.0,35187.0,18.513291,0.268728,NaN,829.096251,70.0,82083.0,43.195397,0.325711,NaN,1004.903096,3.05,NaN,14720.6544,15.0,17601.0,9.257502,3.354953,NaN,10350.912049,30.0,35187.0,18.513291,3.379836,NaN,10427.684272,70.0,82083.0,43.195397,3.471993,NaN,10712.012489,3.9,NaN,14720.6544,15.0,17601.0,9.257502,0.227241,10.286113,1325.457343,30.0,35187.0,18.513291,0.227241,20.570324,1325.457343,70.0,82083.0,43.195397,0.227241,47.994885,1325.457343,3.9
2,EgKu,2.0,EFH,gering,Kurve,NaN,10000.0,8500.0,600.0,560.0,340.0,781.0,120.0,0.0901,NaN,NaN,390.5,312.4,1171.5,NaN,901.0,0.0901,0.12915,NaN,1.5,1291.5,1033.2,1562.0,1249.6,937.2,20.0,917.2,NaN,781.0,1085.6,1284.0,3150.6,4095.2,0.769340,NaN,100.0,100.0,200.0,NaN,8.0,NaN,51.0,157.0,196.0,18.376471,8.0,32.650448,75.0,NaN,Sattel,781.0,921.2,NaN,NaN,390.5,NaN,16.0,0.2,187.44,288.0,611.2,64.0,530.7,8.0,NaN,NaN,281.16,5501.364,456.0,224.0,NaN,0.0,NaN,11767.4832,15.0,14073.0,7.400660,0.257064,NaN,634.000714,30.0,28131.0,14.799607,0.268753,NaN,662.830394,70.0,65619.0,34.530133,0.325726,NaN,803.342271,3.05,NaN,11767.4832,15.0,14073.0,7.400660,3.282810,NaN,8096.446350,30.0,28131.0,14.799607,3.307702,NaN,8157.836620,70.0,65619.0,34.530133,3.399888,NaN,8385.197312,3.9,NaN,11767.4832,15.0,14073.0,7.400660,0.225172,8.222955,1049.904681,30.0,28131.0,14.799607,0.225172,16.444008,1049.904681,70.0,65619.0,34.530133,0.240730,38.366815,1122.450673,3.9
3,EgWe,3.0,EFH,gering,Wendehammer,NaN,10000.0,8493.0,764.0,423.0,320.0,781.0,120.0,0.0901,NaN,NaN,390.5,312.4,1171.5,NaN,901.0,0.0901,0.12915,NaN,1.5,1291.5,1033.2,1562.0,1249.6,937.2,20.0,917.2,NaN,781.0,1085.6,1284.0,3150.6,4095.2,0.769340,NaN,90.0,100.0,190.0,NaN,8.0,NaN,51.0,157.0,196.0,18.376471,8.0,41.574904,95.5,NaN,Sattel,781.0,921.2,NaN,NaN,390.5,NaN,16.0,0.2,187.44,288.0,611.2,64.0,530.7,8.0,NaN,NaN,281.16,5501.364,456.0,224.0,NaN,0.0,NaN,11767.4832,15.0,14073.0,7.400660,0.257064,NaN,634.000714,30.0,28131.0,14.799607,0.268753,NaN,662.830394,70.0,65619.0,34.530133,0.325726,NaN,803.342271,3.05,NaN,11767.4832,15.0,14073.0,7.400660,3.270709,NaN,8066.602195,30.0,28131.0,14.799607,3.295540,NaN,8127.842732,70.0,65619.0,34.530133,3.387727,NaN,8355.203424,3.9,NaN,11767.4832,15.0,14073.0,7.400660,0.224818,8.222955,1048.257382,30.0,28131.0,14.799607,0.224818,16.444008,1048.257382,70.0,65619.0,34.530133,0.240377,38.366815,1120.803373,3.9
4,EmKr,4.0,EFH,mittel,Kreuzung,NaN,10000.0,7225.0,1164.0,931.0,680.0,1172.0,180.0,0.1352,NaN,NaN,586.0,468.8,1758.0,NaN,1352.0,0.1352,0.25240,NaN,2.0,2524.0,2019.2,2930.0,2344.0,1875.2,30.0,1845.2,NaN,1172.0,1326.0,3129.6,5627.6,8492.4,0.662663,NaN,200.0,150.0,350.0,NaN,12.0,NaN,51.0,157.0,196.0,36.768627,12.0,31.657423,97.0,NaN,Sattel,1172.0,1839.2,NaN,NaN,586.0,NaN,24.0,0.2,375.04,432.0,916.8,96.0,1253.2,18.0,NaN,NaN,562.56,11007.424,684.0,336.0,NaN,0.0,NaN,23545.0112,15.0,28143.0,14.805923,0.223950,NaN,1105.134620,30.0,56271.0,29.610133,0.254174,NaN,1254.280728,70.0,131279.0,69.088028,0.318058,NaN,1569.532598,3.05,NaN,23545.0112,15.0,28143.0,14.805923,2.141290,NaN,10566.702962,30.0,56271.0,29.610133,2.183865,NaN,10776.798997,70.0,131279.0,69.088028,2.280712,NaN,11254.715930,3.9,NaN,23545.0112,15.0,28143.0,14.805923,0.186690,16.451025,1741.693432,30.0,56271.0,29.610133,0.196847,32.900148,1836.456672,70.0,131279.0,69.088028,0.216916,76.764476,2023.682096,3.9

In [17]:
print(df_4_Flaechencode["Bewohner Kachel insg. (rechnerisch)"].dtype)

float64

In [18]:
print(df_4_Flaechencode.columns.to_list())

['Flächen-Code', 'Nr. ', 'Gebäudetyp', 'Dichte', 'Straßenform/ Erschließungstyp', 'Unnamed: 5', 'Gesamtfläche ', 'Baufelder und sonstige Freiflächen                    ', 'Straßenflächen (öffentlich)', 'Rad- und Gehweg- flächen (öffentlich)', 'Oberirdische Stellplatzflächen (öffentlich)', 'Grundflächen Wohngebäude (brutto)', 'Garagengrundflächen (brutto) (1)', 'Anteil überbaute Flächen gesamt', 'Flächen Tiefgaragen (brutto) (2)                  ', 'Flächen Tiefgaragen (netto) (3)', 'Kellerflächen (brutto) (4)', 'Kellerflächen netto (5)', 'Aushubvolumen (m3)', 'Unnamed: 19', 'Summe aller überbauter Teilflächen (m²)', 'Quartiers-GRZ', 'Quartiers-GFZ', 'Unnamed: 23', 'Obergeschosse ', 'BGF (m²) inkl. oberirdische Garagen', 'NRF (m²) inkl. oberirdische Garagen (5)', 'BGF (m²) Wohnen (inkl. Keller)', 'Nettoraumfläche NRF (m2)', ' Nettowohnfläche NUF (m2)', 'davon NRF (m²) Balkone (6)', 'davon NRF (m²) Wohnen Innenräume (7)', 'Unnamed: 32', 'Grundflächen (brutto)', 'Dachflächen', 'Fassadenflächen', 'Hüllflächen gesamt          (mit Bodenplatte)', 'Volumen (m³)', 'A/V-Verhältnis Wohngebäude', 'Unnamed: 39', 'Länge Straßen               (mittig Straße)', 'Zuwege zu den Gebäuden (von Häusern zur Straßenmitte) (lfm)', 'Netzlänge gesamt (Straßenlängen (mittig) + Zuwege) (lfm)', 'Unnamed: 43', 'Anzahl Gebäude/ Kachel', 'Unnamed: 45', 'Nettowohnfläche pro Person (8) (statistisch)', 'WFL/WE (m²) (9) (statistisch)', 'BGF/WE (10) (rechnerisch aus Statistik abgeleitet)', 'Bewohner Kachel insg. (rechnerisch)', 'WE Kachel insg. (rechnerisch)', 'Straßenfläche pro Bewohner (m²)', 'Straßenfläche pro WE (m²)', 'Unnamed: 53', 'Dachtyp', 'Bodenplatte - 320', 'Boden (m2) (alle Geschosse) - 320', 'Außenwände (m2) - 330', 'Außenwände abzügli. Fenster & Türen (m2) - 330', 'Kellerboden brutto (m2) - 320', 'Kellerwände (m2) - 330', 'Außentüren (Stk) - 330', 'Fensterflächenanteil (%) - 330', 'Außenfenster (m2) - 330', 'Tragende Innenwände abzügl. Türen (m2) - 340', 'Nichttragende Innenwände abzügl. Innentüren (m2) - 340', 'Innentüren (Stk) - 340', 'Decken (m2) - 350', 'Treppen (Stk) - 350', 'Dachkonstruktion (m2) - 360', 'Unnamed: 70', 'Lüftungskanal Länge (lm)', 'Stromkabel lm ', 'Steckdosen (Stk) ', 'Lichtschalter (Stk)', 'Unnamed: 75', 'Aufzug (Stk)', 'Unnamed: 77', 'Trinkwarmwasserbedarf (60 °C) gesamt in MWh pro Jahr', 'E-Kennwert', 'Wärmebedarf gesamt kWh/a', 'Installierte Leistung thermisch kW', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA', 'E-Kennwert.1', 'Wärmebedarf gesamt kWh/a.1', 'Installierte Leistung thermisch kW.1', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.1', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.1', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.1', 'E-Kennwert.2', 'Wärmebedarf gesamt kWh/a.2', 'Installierte Leistung thermisch kW.2', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.2', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.2', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.2', 'Jahresarbeitszahl Luft-Wasser-Wärmepumpe', 'Unnamed: 98', 'Trinkwarmwasserbedarf (60 °C) gesamt in MWh pro Jahr.1', 'E-Kennwert.3', 'Wärmebedarf gesamt kWh/a.3', 'Installierte Leistung thermisch kW.3', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.3', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.3', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.3', 'E-Kennwert.4', 'Wärmebedarf gesamt kWh/a.4', 'Installierte Leistung thermisch kW.4', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.4', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.4', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.4', 'E-Kennwert.5', 'Wärmebedarf gesamt kWh/a.5', 'Installierte Leistung thermisch kW.5', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.5', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.5', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.5', 'Jahresarbeitszahl Luft-Wasser-Wärmepumpe.1', 'Unnamed: 119', 'Trinkwarmwasserbedarf (60 °C) gesamt in MWh pro Jahr.2', 'E-Kennwert.6', 'Wärmebedarf gesamt kWh/a.6', 'Installierte Leistung thermisch kW.6', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.6', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.6', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.6', 'E-Kennwert.7', 'Wärmebedarf gesamt kWh/a.7', 'Installierte Leistung thermisch kW.7', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.7', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.7', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.7', 'E-Kennwert.8', 'Wärmebedarf gesamt kWh/a.8', 'Installierte Leistung thermisch kW.8', 'CO2-Ausstoß Betrieb pro Nutzfläche kg/m²/a.8', 'Betriebsenergie (Stromverbrauch, Gasverbrauch, etc.) in kWh/a.8', 'GWP-CO2-Äquvivalent (nur Konstruktion) in kg*a - Werte aus eLCA.8', 'Jahresarbeitszahl Luft-Wasser-Wärmepumpe.2']

In [19]:
# Clean tabs and spaces from column names
df_4_Flaechencode.columns = (
    df_4_Flaechencode.columns
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [20]:
relevant_cols = [
    "Flächen-Code",
    "Nr.",
    "Gebäudetyp",
    "Straßenform/ Erschließungstyp",
    "Gesamtfläche",
    "Straßenflächen (öffentlich)",
    "Rad- und Gehweg- flächen (öffentlich)",
    "Oberirdische Stellplatzflächen (öffentlich)",
    "Grundflächen Wohngebäude (brutto)",
    "Flächen Tiefgaragen (brutto) (2)",
    "Flächen Tiefgaragen (netto) (3)",
    "Quartiers-GRZ",
    "Quartiers-GFZ",
    "Obergeschosse",
    "BGF (m²) inkl. oberirdische Garagen",
    "BGF (m²) Wohnen (inkl. Keller)",
    "Nettowohnfläche NUF (m2)",
    "Nettoraumfläche NRF (m2)",
    "A/V-Verhältnis Wohngebäude",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)"
]

df_4 = df_4_Flaechencode[relevant_cols].copy()

df_4.head()

,Flächen-Code,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehweg- flächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EgKr,1.0,EFH,Kreuzung,10000.0,1164.0,931.0,680.0,977.0,NaN,NaN,0.1127,0.16155,1.5,1615.5,1954.0,1172.4,1563.2,0.769486,10.0,51.0,22.988235,10.0
2,EgKu,2.0,EFH,Kurve,10000.0,600.0,560.0,340.0,781.0,NaN,NaN,0.0901,0.12915,1.5,1291.5,1562.0,937.2,1249.6,0.769340,8.0,51.0,18.376471,8.0
3,EgWe,3.0,EFH,Wendehammer,10000.0,764.0,423.0,320.0,781.0,NaN,NaN,0.0901,0.12915,1.5,1291.5,1562.0,937.2,1249.6,0.769340,8.0,51.0,18.376471,8.0
4,EmKr,4.0,EFH,Kreuzung,10000.0,1164.0,931.0,680.0,1172.0,NaN,NaN,0.1352,0.25240,2.0,2524.0,2930.0,1875.2,2344.0,0.662663,12.0,51.0,36.768627,12.0

In [21]:
print(len(df_8["Flächen-Code"].unique()))

55

In [22]:
# Merge df_8 and df_4
df_4_8 = df_8.merge(df_4, on="Flächen-Code")

df_4_8.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehweg- flächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch)
0,EH15NgGi,EgGi,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
1,EH15LgGi,EgGi,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
2,EH15EgGi,EgGi,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
3,EH30NgGi,EgGi,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
4,EH30LgGi,EgGi,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0

In [23]:
print(df_4_8["Erschließung (Sied.)"].unique())
df_4_8["Erschließung (Sied.)"] = df_4_8["Erschließung (Sied.)"].str.strip()
print(df_4_8["Erschließung (Sied.)"].unique())

<StringArray>
['Gitter', 'Schlaufe ', 'Sackgasse', 'Schlaufe', nan]
Length: 5, dtype: str
<StringArray>
['Gitter', 'Schlaufe', 'Sackgasse', nan]
Length: 4, dtype: str

In [24]:
"""
------------------------------------------------------------------------------
Table 9: ALL_NGF_Kod_Matrix_Siedlung / GWP per qm
------------------------------------------------------------------------------
"""

# 6ha-Table
df_9_Matrix = pd.read_excel("../data/raw/Q-LCA_FD3_Bilanzierungstool.xlsx", sheet_name="9 - ALL_NGF_Kod_Matrix_Siedlung", skiprows =1)
df_9_Matrix.columns = df_9_Matrix.columns.str.replace("\n", " ")

df_9_Matrix.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Typ.1,Bauart.1,Energiebedarf.1,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GRZ,GFZ,GWP/ qm Basic + Aushub +Strom,GWP/ qm Basic + Aushub,GWP/ EW Basic +Aushub +Strom,GWP/ EW Basic +Aushub,GWP für Bauwerk (KG 300) mit Aushub,GWP für Bauwerk (KG 300) ohne Aushub,310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außen- wand,334 Außen-türen,339 Keller- wände,334 Fenster,341 Innen wände tragend (inkl. Aufzugschacht),342 Innen-wände,344 Innen-türen,351 Decken,351 Treppe,361 Dach,GWP für Haus- technik (KG 400),"410 Abwasser, Gas",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500) mit Aushub,GWP für gesamte Geb.- Erschliessung (KG 500) ohne Aushub,500 Quartiers strom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Ragweg,522 Straße,524 Stell- plätze,524 Hoch- garagen,524 Tief- garagen,Summe Wärmeversorgung 420 + B6,GWP Wärmeversorgung B6,GWP Haushalts- strom,Unnamed: 53
0,EH15NGGi,EGGi,EFH,Holz,15 kWh,Einfamilienhaus,Holz,15 kWh,Nahwärme kalt,Gering,Kreuzung,Gitter,0.11,0.16,18.031299,18.031299,1226.128298,1226.128298,6.277931,6.157181,0.12075,1.38125,0.582393,0.820405,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.336860,7.059247,0.091159,6.621617,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,8.635325,2.013708,0.0,NaN
1,EH15LGGi,EGGi,EFH,Holz,15 kWh,NaN,NaN,NaN,LW Wärmepumpe,Gering,Kreuzung,Gitter,0.11,0.16,12.478105,12.478105,848.511113,848.511113,6.277931,6.157181,0.12075,1.38125,0.582393,0.820405,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.336860,0.944856,0.091159,0.507226,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,3.082131,2.574905,0.0,NaN
2,EH15EGGi,EGGi,EFH,Holz,15 kWh,NaN,NaN,NaN,Erdgas,Gering,Kreuzung,Gitter,0.11,0.16,14.859516,14.859516,1010.447116,1010.447116,6.277931,6.157181,0.12075,1.38125,0.582393,0.820405,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.336860,1.285542,0.091159,0.847913,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,5.463543,4.615630,0.0,NaN
3,EH30NGGi,EGGi,EFH,Holz,30 kWh,NaN,NaN,30 kWh,Nahwärme kalt,Gering,Kreuzung,Gitter,0.11,0.16,18.968152,18.968152,1289.834324,1289.834324,6.069519,5.948769,0.12075,1.27500,0.582393,0.744285,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.310818,7.108359,0.091159,6.670729,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,9.780591,3.109862,0.0,NaN
4,EH30LGGi,EGGi,EFH,Holz,30 kWh,NaN,NaN,NaN,LW Wärmepumpe,Gering,Kreuzung,Gitter,0.11,0.16,13.694489,13.694489,931.225258,931.225258,6.069519,5.948769,0.12075,1.27500,0.582393,0.744285,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.310818,0.968013,0.091159,0.530384,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,4.506928,3.976544,0.0,NaN

In [25]:
# Clean tabs and spaces from column names
df_9_Matrix.columns = (
    df_9_Matrix.columns
    .str.replace("\n", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [26]:
df_9_Matrix.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Typ.1,Bauart.1,Energiebedarf.1,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GRZ,GFZ,GWP/ qm Basic + Aushub +Strom,GWP/ qm Basic + Aushub,GWP/ EW Basic +Aushub +Strom,GWP/ EW Basic +Aushub,GWP für Bauwerk (KG 300) mit Aushub,GWP für Bauwerk (KG 300) ohne Aushub,310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außen- wand,334 Außen-türen,339 Keller- wände,334 Fenster,341 Innen wände tragend (inkl. Aufzugschacht),342 Innen-wände,344 Innen-türen,351 Decken,351 Treppe,361 Dach,GWP für Haus- technik (KG 400),"410 Abwasser, Gas",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500) mit Aushub,GWP für gesamte Geb.- Erschliessung (KG 500) ohne Aushub,500 Quartiers strom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Ragweg,522 Straße,524 Stell- plätze,524 Hoch- garagen,524 Tief- garagen,Summe Wärmeversorgung 420 + B6,GWP Wärmeversorgung B6,GWP Haushalts- strom,Unnamed: 53
0,EH15NGGi,EGGi,EFH,Holz,15 kWh,Einfamilienhaus,Holz,15 kWh,Nahwärme kalt,Gering,Kreuzung,Gitter,0.11,0.16,18.031299,18.031299,1226.128298,1226.128298,6.277931,6.157181,0.12075,1.38125,0.582393,0.820405,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.336860,7.059247,0.091159,6.621617,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,8.635325,2.013708,0.0,NaN
1,EH15LGGi,EGGi,EFH,Holz,15 kWh,NaN,NaN,NaN,LW Wärmepumpe,Gering,Kreuzung,Gitter,0.11,0.16,12.478105,12.478105,848.511113,848.511113,6.277931,6.157181,0.12075,1.38125,0.582393,0.820405,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.336860,0.944856,0.091159,0.507226,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,3.082131,2.574905,0.0,NaN
2,EH15EGGi,EGGi,EFH,Holz,15 kWh,NaN,NaN,NaN,Erdgas,Gering,Kreuzung,Gitter,0.11,0.16,14.859516,14.859516,1010.447116,1010.447116,6.277931,6.157181,0.12075,1.38125,0.582393,0.820405,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.336860,1.285542,0.091159,0.847913,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,5.463543,4.615630,0.0,NaN
3,EH30NGGi,EGGi,EFH,Holz,30 kWh,NaN,NaN,30 kWh,Nahwärme kalt,Gering,Kreuzung,Gitter,0.11,0.16,18.968152,18.968152,1289.834324,1289.834324,6.069519,5.948769,0.12075,1.27500,0.582393,0.744285,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.310818,7.108359,0.091159,6.670729,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,9.780591,3.109862,0.0,NaN
4,EH30LGGi,EGGi,EFH,Holz,30 kWh,NaN,NaN,NaN,LW Wärmepumpe,Gering,Kreuzung,Gitter,0.11,0.16,13.694489,13.694489,931.225258,931.225258,6.069519,5.948769,0.12075,1.27500,0.582393,0.744285,0.107472,0.489413,0.475893,0.201126,0.229708,0.010747,0.518141,0.003774,1.310818,0.968013,0.091159,0.530384,0.189,0.15747,0.0,2.680413,2.670883,0.059669,0.145855,0.005821,0.003708,0.708732,0.886105,0.548106,0.322416,0.0,4.506928,3.976544,0.0,NaN

In [27]:
print(df_9_Matrix.columns.to_list())

['Siedlungs-Code', 'Flächen-Code', 'Typ', 'Bauart', 'Energiebedarf', 'Typ.1', 'Bauart.1', 'Energiebedarf.1', 'Versorgungsart', 'Dichte', 'Erschließung (Segm.)', 'Erschließung (Sied.)', 'GRZ', 'GFZ', 'GWP/ qm Basic + Aushub +Strom', 'GWP/ qm Basic + Aushub', 'GWP/ EW Basic +Aushub +Strom', 'GWP/ EW Basic +Aushub', 'GWP für Bauwerk (KG 300) mit Aushub', 'GWP für Bauwerk (KG 300) ohne Aushub', '310 Erdaushub Keller', '322 Bodenplatte', '325 Bodenbelag', '331 Außen- wand', '334 Außen-türen', '339 Keller- wände', '334 Fenster', '341 Innen wände tragend (inkl. Aufzugschacht)', '342 Innen-wände', '344 Innen-türen', '351 Decken', '351 Treppe', '361 Dach', 'GWP für Haus- technik (KG 400)', '410 Abwasser, Gas', '420 Wärme- versorgung', '430 Lüftung', '440 Strom', '460 Aufzug', 'GWP für gesamte Geb.- Erschliessung (KG 500) mit Aushub', 'GWP für gesamte Geb.- Erschliessung (KG 500) ohne Aushub', '500 Quartiers strom', '500 Quartierswasserleitung', '510 Erdaushub Leitungen', '510 Erdaushub Garagen', '521 Gehweg Ragweg', '522 Straße', '524 Stell- plätze', '524 Hoch- garagen', '524 Tief- garagen', 'Summe Wärmeversorgung 420 + B6', 'GWP Wärmeversorgung B6', 'GWP Haushalts- strom', 'Unnamed: 53']

In [28]:
relevant_cols = [
    "Siedlungs-Code",
    "Flächen-Code",
    "GWP/ qm Basic + Aushub +Strom"
]

df_9 = df_9_Matrix[relevant_cols].copy()

df_9.head()

  Siedlungs-Code Flächen-Code  GWP/ qm Basic + Aushub +Strom
0       EH15NGGi         EGGi                      18.031299
1       EH15LGGi         EGGi                      12.478105
2       EH15EGGi         EGGi                      14.859516
3       EH30NGGi         EGGi                      18.968152
4       EH30LGGi         EGGi                      13.694489

In [29]:
# Rename column

df_9 = df_9.rename(columns={

    "GWP/ qm Basic + Aushub +Strom": "GWP / m² NRF"

})

df_9.head()

  Siedlungs-Code Flächen-Code  GWP / m² NRF
0       EH15NGGi         EGGi     18.031299
1       EH15LGGi         EGGi     12.478105
2       EH15EGGi         EGGi     14.859516
3       EH30NGGi         EGGi     18.968152
4       EH30LGGi         EGGi     13.694489

In [30]:
df_9["GWP / m² NRF"].dtypes

dtype('float64')

In [31]:
df_4_8.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehweg- flächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch)
0,EH15NgGi,EgGi,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
1,EH15LgGi,EgGi,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
2,EH15EgGi,EgGi,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
3,EH30NgGi,EgGi,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0
4,EH30LgGi,EgGi,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0

In [32]:
print(df_4_8["Siedlungs-Code"].dtype)
print(df_9["Siedlungs-Code"].dtype)

str
str

In [33]:
# Siedlungs-Code / neighbourhood code
df_4_8["Siedlungs-Code"] = df_4_8["Siedlungs-Code"].str.strip().str.upper()
df_9["Siedlungs-Code"] = df_9["Siedlungs-Code"].str.strip().str.upper()

# Flächen-Code / area code
df_4_8["Flächen-Code"] = df_4_8["Siedlungs-Code"].str.strip().str.upper()
df_9["Flächen-Code"] = df_9["Siedlungs-Code"].str.strip().str.upper()

In [34]:
# Merge df_4_8 + df_9

df_QLCA = df_4_8.merge(df_9, on=["Siedlungs-Code", "Flächen-Code"], how= "left")

df_QLCA.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehweg- flächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF
0,EH15NGGI,EH15NGGI,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.031299
1,EH15LGGI,EH15LGGI,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,12.478105
2,EH15EGGI,EH15EGGI,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,14.859516
3,EH30NGGI,EH30NGGI,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.968152
4,EH30LGGI,EH30LGGI,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,13.694489

In [35]:
# Tiefgaragen yes / no?

print(df_QLCA["Flächen Tiefgaragen (brutto) (2)"].dtypes)
print(df_QLCA["Flächen Tiefgaragen (netto) (3)"].dtypes)
print(df_QLCA["Flächen Tiefgaragen (brutto) (2)"].value_counts(dropna=False))
print(df_QLCA["Flächen Tiefgaragen (netto) (3)"].value_counts(dropna=False))

float64
float64
Flächen Tiefgaragen (brutto) (2)
NaN             498
7177.846154      54
12760.615385     36
11514.461538     18
26119.384615     18
9595.384615      18
18177.230769     18
10766.769231     18
18941.538462     18
21533.538462     18
14355.692308     18
32649.230769     18
15884.307692     18
22721.538462     18
16416.000000     18
23676.923077     18
26916.923077     18
23926.153846     18
39179.076923     18
19855.384615     18
19938.461538     18
27265.846154     18
20520.000000     18
17944.615385     18
28412.307692     18
Name: count, dtype: int64
Flächen Tiefgaragen (netto) (3)
NaN             498
5742.276923      54
10208.492308     36
9211.569231      18
20895.507692     18
7676.307692      18
14541.784615     18
8613.415385      18
15153.230769     18
17226.830769     18
11484.553846     18
26119.384615     18
12707.446154     18
18177.230769     18
13132.800000     18
18941.538462     18
21533.538462     18
19140.923077     18
31343.261538     18
15884.307692     18
15950.769231     18
21812.676923     18
16416.000000     18
14355.692308     18
22729.846154     18
Name: count, dtype: int64

In [36]:
# Add column "Tiefgarage"

df_QLCA["Tiefgarage"] = df_QLCA["Flächen Tiefgaragen (brutto) (2)"].notna()

df_QLCA.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innen wände,344 Innen türen,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärme- versorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stell -plätze,524 Hoch garagen,524 Tief garagen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehweg- flächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage
0,EH15NGGI,EH15NGGI,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.031299,False
1,EH15LGGI,EH15LGGI,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,12.478105,False
2,EH15EGGI,EH15EGGI,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,14.859516,False
3,EH30NGGI,EH30NGGI,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.968152,False
4,EH30LGGI,EH30LGGI,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,13.694489,False

In [37]:
print(df_QLCA.columns.tolist())

['Siedlungs-Code', 'Flächen-Code', 'Typ', 'Bauart', 'Energiebedarf', 'Versorgungsart', 'Dichte', 'Erschließung (Segm.)', 'Erschließung (Sied.)', 'GWP', 'GWP ohne Strom', 'GWP für Bauwerk (KG 300)', '310 Erdaushub Keller', '322 Bodenplatte', '325 Bodenbelag', '331 Außenwand', '334 Außentüren', '339 Kellerwände', '334 Fenster', '341 Innenwände tragend (inkl. Aufzugschacht)', '342 Innen wände', '344 Innen türen', '351 Decken', '351 Treppe', '361 Dach', 'GWP für Haustechnik (KG 400)', '410 Abwasser, Trinkwasser', '420 Wärme- versorgung', '430 Lüftung', '440 Strom', '460 Aufzug', 'GWP für gesamte Geb.- Erschliessung (KG 500)', '500 Quartiersstrom', '500 Quartierswasserleitung', '510 Erdaushub Leitungen', '510 Erdaushub Garagen', '521 Gehweg Radweg', '522 Straße', '524 Stell -plätze', '524 Hoch garagen', '524 Tief garagen', 'Summe Betrieb & Nutzstrom', 'GWP für Wärmeversorgung (B6)', 'GWP für Nutzstrom', 'Nr.', 'Gebäudetyp', 'Straßenform/ Erschließungstyp', 'Gesamtfläche', 'Straßenflächen (öffentlich)', 'Rad- und Gehweg- flächen (öffentlich)', 'Oberirdische Stellplatzflächen (öffentlich)', 'Grundflächen Wohngebäude (brutto)', 'Flächen Tiefgaragen (brutto) (2)', 'Flächen Tiefgaragen (netto) (3)', 'Quartiers-GRZ', 'Quartiers-GFZ', 'Obergeschosse', 'BGF (m²) inkl. oberirdische Garagen', 'BGF (m²) Wohnen (inkl. Keller)', 'Nettowohnfläche NUF (m2)', 'Nettoraumfläche NRF (m2)', 'A/V-Verhältnis Wohngebäude', 'Anzahl Gebäude/ Kachel', 'Nettowohnfläche pro Person (8) (statistisch)', 'Bewohner Kachel insg. (rechnerisch)', 'WE Kachel insg. (rechnerisch)', 'GWP / m² NRF', 'Tiefgarage']

In [38]:
df_QLCA = df_QLCA.rename(columns={
    "524 Tief garagen": "524 Tiefgaragen",
    "342 Innen wände": "342 Innenwände",
    "344 Innen türen": "344 Innentüren",
    "420 Wärme- versorgung": "420 Wärmeversorgung",
    "524 Stell -plätze": "524 Stellplätze",
    "524 Hoch garagen": "524 Hochgaragen",
    "524 Tief garagen": "524 Tiefgaragen",
    "Rad- und Gehweg- flächen (öffentlich)": "Rad- und Gehwegflächen (öffentlich)"
})

df_QLCA.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage
0,EH15NGGI,EH15NGGI,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.031299,False
1,EH15LGGI,EH15LGGI,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,12.478105,False
2,EH15EGGI,EH15EGGI,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,14.859516,False
3,EH30NGGI,EH30NGGI,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.968152,False
4,EH30LGGI,EH30LGGI,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,13.694489,False

In [39]:
df_QLCA["524 Tiefgaragen"].dtypes

dtype('float64')

In [40]:
print(df_QLCA["524 Tiefgaragen"].unique())

[     0.          66899.02153846  41703.28615385 151753.62461538
  55749.18461538 105609.71076923  62554.92923077 110050.33846154
 125109.85846154  83406.57230769 189692.03076923  92287.82769231
  74139.17538462 132012.13846154  95376.96       137562.92307692
 156387.32307692 139010.95384615 227630.43692308 115359.78461538
 115842.46153846 158414.56615385 119221.2        104258.21538462
 165075.50769231  55234.32923077]

In [41]:
"""
------------------------------------------------------------------------------
Verkehrsfläche gesamt
------------------------------------------------------------------------------
"""

df_QLCA["Verkehrsfläche gesamt m²"] = df_QLCA["Straßenflächen (öffentlich)"] + df_QLCA["Rad- und Gehwegflächen (öffentlich)"] + df_QLCA["Oberirdische Stellplatzflächen (öffentlich)"]

In [42]:
"""
------------------------------------------------------------------------------
Add columns: GWP per Person
------------------------------------------------------------------------------
"""

denom = df_QLCA["Bewohner Kachel insg. (rechnerisch)"]

# --- GWP ---
df_QLCA["Person_GWP"] = (df_QLCA["GWP"] / denom).round(2)

df_QLCA["Person_GWP (GWP ohne Strom)"] = (
    df_QLCA["GWP ohne Strom"] / denom
).round(2)

# --- KG 300 ---
df_QLCA["Person_GWP (KG 300)"] = (
    df_QLCA["GWP für Bauwerk (KG 300)"] / denom
).round(2)

df_QLCA["Person_GWP (310 Erdaushub Keller)"] = (
    df_QLCA["310 Erdaushub Keller"] / denom
).round(2)

df_QLCA["Person_GWP (322 Bodenplatte)"] = (
    df_QLCA["322 Bodenplatte"] / denom
).round(2)

df_QLCA["Person_GWP (325 Bodenbelag)"] = (
    df_QLCA["325 Bodenbelag"] / denom
).round(2)

df_QLCA["Person_GWP (331 Außenwand)"] = (
    df_QLCA["331 Außenwand"] / denom
).round(2)

df_QLCA["Person_GWP (334 Außentüren)"] = (
    df_QLCA["334 Außentüren"] / denom
).round(2)

df_QLCA["Person_GWP (339 Kellerwände)"] = (
    df_QLCA["339 Kellerwände"] / denom
).round(2)

df_QLCA["Person_GWP (334 Fenster)"] = (
    df_QLCA["334 Fenster"] / denom
).round(2)

df_QLCA["Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht))"] = (
    df_QLCA["341 Innenwände tragend (inkl. Aufzugschacht)"] / denom
).round(2)

df_QLCA["Person_GWP (342 Innenwände)"] = (
    df_QLCA["342 Innenwände"] / denom
).round(2)

df_QLCA["Person_GWP (344 Innentüren)"] = (
    df_QLCA["344 Innentüren"] / denom
).round(2)

df_QLCA["Person_GWP (351 Decken)"] = (
    df_QLCA["351 Decken"] / denom
).round(2)

df_QLCA["Person_GWP (351 Treppe)"] = (
    df_QLCA["351 Treppe"] / denom
).round(2)

df_QLCA["Person_GWP (361 Dach)"] = (
    df_QLCA["361 Dach"] / denom
).round(2)

# --- KG 400 ---
df_QLCA["Person_GWP (KG 400)"] = (
    df_QLCA["GWP für Haustechnik (KG 400)"] / denom
).round(2)

df_QLCA["Person_GWP (410 Abwasser, Trinkwasser)"] = (
    df_QLCA["410 Abwasser, Trinkwasser"] / denom
).round(2)

df_QLCA["Person_GWP (420 Wärmeversorgung)"] = (
    df_QLCA["420 Wärmeversorgung"] / denom
).round(2)

df_QLCA["Person_GWP (430 Lüftung)"] = (
    df_QLCA["430 Lüftung"] / denom
).round(2)

df_QLCA["Person_GWP (440 Strom)"] = (
    df_QLCA["440 Strom"] / denom
).round(2)

df_QLCA["Person_GWP (460 Aufzug)"] = (
    df_QLCA["460 Aufzug"] / denom
).round(2)

# --- KG 500 ---
df_QLCA["Person_GWP (KG 500)"] = (
    df_QLCA["GWP für gesamte Geb.- Erschliessung (KG 500)"] / denom
).round(2)

df_QLCA["Person_GWP (500 Quartiersstrom)"] = (
    df_QLCA["500 Quartiersstrom"] / denom
).round(2)

df_QLCA["Person_GWP (500 Quartierswasserleitung)"] = (
    df_QLCA["500 Quartierswasserleitung"] / denom
).round(2)

df_QLCA["Person_GWP (510 Erdaushub Leitungen)"] = (
    df_QLCA["510 Erdaushub Leitungen"] / denom
).round(2)

df_QLCA["Person_GWP (510 Erdaushub Garagen)"] = (
    df_QLCA["510 Erdaushub Garagen"] / denom
).round(2)

df_QLCA["Person_GWP (521 Gehweg Radweg)"] = (
    df_QLCA["521 Gehweg Radweg"] / denom
).round(2)

df_QLCA["Person_GWP (522 Straße)"] = (
    df_QLCA["522 Straße"] / denom
).round(2)

df_QLCA["Person_GWP (524 Stellplätze)"] = (
    df_QLCA["524 Stellplätze"] / denom
).round(2)

df_QLCA["Person_GWP (524 Hochgaragen)"] = (
    df_QLCA["524 Hochgaragen"] / denom
).round(2)

df_QLCA["Person_GWP (524 Tiefgaragen)"] = (
    df_QLCA["524 Tiefgaragen"] / denom
).round(2)

df_QLCA["Person_GWP (Summe Betrieb & Nutzstrom)"] = (
    df_QLCA["Summe Betrieb & Nutzstrom"] / denom
).round(2)

# --- B6 ---
df_QLCA["Person_GWP (B6)"] = (
    df_QLCA["GWP für Wärmeversorgung (B6)"] / denom
).round(2)

df_QLCA["Person_GWP (GWP für Nutzstrom)"] = (
    df_QLCA["GWP für Nutzstrom"] / denom
).round(2)

df_QLCA.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
0,EH15NGGI,EH15NGGI,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.031299,False,16650.0,1226.13,1226.13,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,480.03,6.2,450.27,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,136.93,136.93,0.0
1,EH15LGGI,EH15LGGI,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,12.478105,False,16650.0,848.51,848.51,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,64.25,6.2,34.49,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,175.1,175.09,0.0
2,EH15EGGI,EH15EGGI,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,14.859516,False,16650.0,1010.44,1010.45,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,87.42,6.2,57.66,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,313.86,313.86,0.0
3,EH30NGGI,EH30NGGI,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.968152,False,16650.0,1289.83,1289.83,412.73,8.21,86.70,39.6,50.61,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,89.14,483.37,6.2,453.61,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,211.47,211.47,0.0
4,EH30LGGI,EH30LGGI,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,13.694489,False,16650.0,931.22,931.23,412.73,8.21,86.70,39.6,50.61,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,89.14,65.82,6.2,36.07,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,270.41,270.41,0.0

In [43]:
print(df_QLCA.groupby("Tiefgarage")["GWP"].mean())
print(df_QLCA.groupby("Tiefgarage")["Person_GWP"].mean())
print(df_QLCA.groupby("Tiefgarage")["GWP / m² NRF"].mean())

Tiefgarage
False    277015.514056
True     939808.514403
Name: GWP, dtype: Float64
Tiefgarage
False    954.425144
True     794.533045
Name: Person_GWP, dtype: Float64
Tiefgarage
False    15.600352
True     16.240134
Name: GWP / m² NRF, dtype: float64

In [44]:
df_QLCA.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
0,EH15NGGI,EH15NGGI,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.031299,False,16650.0,1226.13,1226.13,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,480.03,6.2,450.27,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,136.93,136.93,0.0
1,EH15LGGI,EH15LGGI,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,12.478105,False,16650.0,848.51,848.51,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,64.25,6.2,34.49,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,175.1,175.09,0.0
2,EH15EGGI,EH15EGGI,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,14.859516,False,16650.0,1010.44,1010.45,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,87.42,6.2,57.66,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,313.86,313.86,0.0
3,EH30NGGI,EH30NGGI,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.968152,False,16650.0,1289.83,1289.83,412.73,8.21,86.70,39.6,50.61,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,89.14,483.37,6.2,453.61,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,211.47,211.47,0.0
4,EH30LGGI,EH30LGGI,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,13.694489,False,16650.0,931.22,931.23,412.73,8.21,86.70,39.6,50.61,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,89.14,65.82,6.2,36.07,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,270.41,270.41,0.0

In [45]:
# CSV
df_QLCA.to_csv("../data/csv/QLCA_data.csv", index = False)

In [46]:
#-------------------------------------------------------------------------------#
# MIn / MAX values
#-------------------------------------------------------------------------------#

In [47]:
print("Max. value:",df_QLCA["GWP"].max())
print("Min. value:",df_QLCA["GWP"].min())
print("Mean value:", df_QLCA["GWP"].mean())


df_QLCA[df_QLCA["GWP"]== 2891682]

Max. value: 2891682
Min. value: 97542
Mean value: 604370.593495935

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
755,BM70EHGI,BM70EHGI,BW,Massiv,70 kWh,Erdgas,hoch,Kreuzung,Gitter,2891682,2.891682e+06,584560.700822,6055.518129,39685.14,85212.387415,74692.084763,11070.941538,8724.6,58172.533714,39096.0,70443.980308,1371.267692,144537.467262,6238.08,39260.7,164635.9,71.82,75668.133494,47917.57824,21365.552138,19612.8,264338,362.481,1368.0,35.364,14842.601502,6647.34,8310.96,5140.8,0.0,227630.436923,1878148,1.878148e+06,0.0,620.0,BW,Gitter,60000.0,6984.0,5586.0,4080.0,21222.0,39179.076923,31343.261538,0.3537,2.1222,6.0,127332.0,143003.630769,101865.6,121553.086154,0.259259,6.0,41.0,2484.526829,1305.969231,23.78946,True,16650.0,1163.88,1163.88,235.28,2.44,15.97,34.3,30.06,4.46,3.51,23.41,15.74,28.35,0.55,58.18,2.51,15.8,66.26,0.03,30.46,19.29,8.6,7.89,106.39,0.15,0.55,0.01,5.97,2.68,3.35,2.07,0.0,91.62,755.94,755.94,0.0

In [48]:
df_QLCA[df_QLCA["GWP"]== 97542]

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
217,EH15LGSA,EH15LGSA,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Wendehammer,Sackgasse,97542,97542.207004,51019.683886,981.0696,11222.38,4731.784,6669.332,873.6,3978.26,3866.534286,1634.88,1867.216,87.36,4209.732,30.68,10866.856,7677.8,741.0,4121.794552,1535.5872,1279.444688,0.0,17924,404.67,866.4,39.48,30.1392,4229.26,6406.96,3326.4,2620.8,0.0,20921,20920.587478,0.0,102.0,EFH,Sackgasse,60000.0,5384.0,3554.0,2640.0,5078.0,NaN,NaN,0.097633,0.13995,1.5,8397.0,10156.0,6093.6,8124.8,0.769396,52.0,51.0,119.482353,52.0,12.00549,False,11578.0,816.37,816.37,427.01,8.21,93.92,39.6,55.82,7.31,33.3,32.36,13.68,15.63,0.73,35.23,0.26,90.95,64.26,6.2,34.5,12.85,10.71,0.0,150.01,3.39,7.25,0.33,0.25,35.4,53.62,27.84,21.93,0.0,175.1,175.09,0.0